### ISSUE TITLE
Error -  Install rekall inside virtualenv

### ISSUE THREAD

**Issue by reynas** [juju4/ansible-rekall#1]
Current host= Linux ubuntu 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I have the following error while installing, I was wondering if you know a fix for this?

TASK [juju4.rekall : Install rekall inside virtualenv] *************************
task path: /home/user/install-rekall-ansible/juju4.rekall/tasks/rekall.yml:37
ESTABLISH LOCAL CONNECTION FOR USER: root
local EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1562848904.87-180454166344691 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1562848904.87-180454166344691 )" )
local PUT /tmp/tmpMvhqgH TO /root/.ansible/tmp/ansible-tmp-1562848904.87-180454166344691/pip
local EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1562848904.87-180454166344691/pip; rm -rf "/root/.ansible/tmp/ansible-tmp-1562848904.87-180454166344691/" > /dev/null 2>&1
FAILED - RETRYING: TASK: juju4.rekall : Install rekall inside virtualenv (2 retries left). Result was: {'invocation': {'module_name': u'pip'}, 'failed': True, 'exception': u'Traceback (most recent call last):\n  File "/root/.ansible/tmp/ansible-tmp-1562848904.87-180454166344691/pip", line 2329, in <module>\n    main()\n  File "/root/.ansible/tmp/ansible-tmp-1562848904.87-180454166344691/pip", line 326, in main\n    has_vcs = bool(name and re.match(r\'(svn|git|hg|bzr)\\+\', name))\n  File "/usr/lib/python2.7/re.py", line 141, in match\n    return _compile(pattern, flags).match(string)\nTypeError: expected string or buffer\n', 'parsed': False}

Thanks!

**Comment by juju4** [comment]
I would recommend switching to python3 as 2 is EOL soon
Else, try manually on system. what happens?

corresponding code is here
https://github.com/juju4/ansible-rekall/blob/master/tasks/rekall.yml#L37
and last run by travis is fine on Ubuntu 18.04
https://travis-ci.org/juju4/ansible-rekall/jobs/558405549#L2196

how do you install this role? with github or galaxy?
galaxy by default is using latest tag which is very old. plan to do a new one soon but in the meantime, use github clone or force HEAD.

**Comment by reynas** [comment]
Hi

I used a freshly installed Ubuntu 18.04 and forced ansible to use python3. The install was successful, but executing rekall failed.


2019-07-15 08:16:49,460:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/tools/ipython.py", line 211, in render
    if not IPython012Support(self.session):
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/tools/ipython.py", line 53, in IPython012Support
    return ipython_support.Shell(user_session)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/ipython_support.py", line 267, in Shell
    shell = RekallShell(config=cfg, user_ns=user_session.locals)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/embed.py", line 159, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 430, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 527, in __init__
    self.init_magics()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/embed.py", line 174, in init_magics
    super(InteractiveShellEmbed, self).init_magics()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 413, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2086, in init_magics
    self.run_line_magic('colors', self.colors)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2123, in run_line_magic
    magic_arg_s = self.var_expand(line, stack_depth)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3117, in var_expand
    ns = self.user_ns.copy()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 1172, in keys
    return list(self)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 1161, in __iter__
    res.update(self["plugins"].__dir__())
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 164, in __dir__
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 164, in <listcomp>
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugin.py", line 403, in GetActiveClasses
    if command_cls.is_active(session):
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/addrspaces/aff4.py", line 125, in __init__
    os.path.join(cache_dir, "aff4_cache")))
TypeError: Set() missing 1 required positional argument: 'value'

2019-07-15 08:16:49,460:CRITICAL:root:Set() missing 1 required positional argument: 'value'. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/tools/ipython.py", line 211, in render
    if not IPython012Support(self.session):
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/tools/ipython.py", line 53, in IPython012Support
    return ipython_support.Shell(user_session)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/ipython_support.py", line 267, in Shell
    shell = RekallShell(config=cfg, user_ns=user_session.locals)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/embed.py", line 159, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 430, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 527, in __init__
    self.init_magics()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/embed.py", line 174, in init_magics
    super(InteractiveShellEmbed, self).init_magics()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 413, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2086, in init_magics
    self.run_line_magic('colors', self.colors)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2123, in run_line_magic
    magic_arg_s = self.var_expand(line, stack_depth)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3117, in var_expand
    ns = self.user_ns.copy()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 1172, in keys
    return list(self)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 1161, in __iter__
    res.update(self["plugins"].__dir__())
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 164, in __dir__
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 164, in <listcomp>
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugin.py", line 403, in GetActiveClasses
    if command_cls.is_active(session):
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/share/env-rekall/lib/python3.6/site-packages/rekall/plugins/addrspaces/aff4.py", line 125, in __init__
    os.path.join(cache_dir, "aff4_cache")))
TypeError: Set() missing 1 required positional argument: 'value'

**Comment by juju4** [comment]
Did you install manually or with the role?
In travis, it works fine https://travis-ci.org/juju4/ansible-rekall/jobs/558405549#L2364

maybe future related https://github.com/juju4/ansible-rekall/blob/master/tasks/rekall.yml#L53
not the role anyway

**Comment by reynas** [comment]
I installed with the role, installation indeed works fine (which is already great, as the manual installation broke on me a lot of times) but as soon as I try to use it with a memory image, rekall breaks.

**Comment by juju4** [comment]
Looking at this again, I think it is related to this upstream issue
https://github.com/google/rekall/issues/493

forcing pyaff4 in role
https://github.com/juju4/ansible-rekall/commit/82b09e362695afbdfa3cfbb3dd047f6ea362401a

please confirm if good on your side

**Comment by juju4** [comment]
Closing.
Please reopen if still an issue
